### ISSUE TITLE
How I make multiple ping and how I setup the time of ping like 1 ping per 10 second

### ISSUE THREAD

**Issue by JohanChungus** [ffrrancis/pingr#4]
how I make multiple ping I see on config.json only 1 can I add more?

**Comment by ffrrancis** [comment]
To ping multiple websites, set up your config.json like this:
```js
{
  "links": ["LINK 1", "LINK 2"]
}
```

To modify the interval in between pings, try this:
```js
pinger.ping([links], 10); // the second arg is the interval
```

This may not work as I haven't messed around with this package and repo for a while lol.

**Comment by ffrrancis** [comment]
Please tell me if my solution works so I can close this issue!!

**Comment by JohanChungus** [comment]
{
  "links": ["https://nexus.5xi.repl.co", "https://pingr.dcn0.repl.co"] 
}
like this? I try its say Successfully Pinged https://nexus.5xi.repl.co,https://pingr.dcn0.repl.co with status 404 found
but the ping interval is work

**Comment by JohanChungus** [comment]
I ask chatgpt to but its still same its say like above

**Comment by ffrrancis** [comment]
Fork the updated version of the repo and see if that works.

Also, I wouldn't recommend asking Chat GPT for coding advice, instead use something like Github Copilot.

**Comment by ffrrancis** [comment]
Did that fix the issue or not?

**Comment by JohanChungus** [comment]
Ok Thanks That Works I Will Close The Comment
